name: Deploy Migrations to Staging

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
      APP_DIR: ./easy-360-app

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        working-directory: ${{ env.APP_DIR }}
        run: supabase start

      - name: Link Supabase Project
        working-directory: ${{ env.APP_DIR }}
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Push DB To Supabase
        working-directory: ${{ env.APP_DIR }}
        run: supabase db push
        
      - name: Deploy Functions to Supabase
        working-directory: ${{ env.APP_DIR }}
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID